+++
title = '''
CWE-584: Return Inside Finally Block
'''
description	= '''
The code has a return statement inside a finally block, which will cause any thrown exception in the try block to be discarded.
'''
weight = 584

[extra]
id = 584
name = '''
Return Inside Finally Block
'''
url = "https://cwe.mitre.org/data/definitions/584.html"
vote = "Virtually Impossible"
class = "Base"
clippy_helps = false
rust_docs_links = [
	
]
+++
Finally isn't in std, though the abstraction is in common libraries