+++
title = "CWE-248: Uncaught Exception\n"
description = "An exception is thrown from a function, but it is not caught.\n"
weight = 248

[extra]
id = 248
name = "Uncaught Exception\n"
url = "https://cwe.mitre.org/data/definitions/248.html"
class = "Base"
rust_docs_links = []
parent = "705"

[extra.vote]
"No Help, or Langs Wont Help" = false
Discouraged = false
"Discouraged via Library" = false
"Discouraged via Borrow Checker" = false
"Discouraged via Debug Mode" = false
"Discouraged via Clippy" = false
"Virtually Impossible" = true

[extra.vector]

+++

One of the big selling-points of Rust safety - they take a hard line on exceptions